language: ruby
sudo: false
rvm:
- ruby-head
- 2.4.1  # Performs deploys. Change condition below when changing this. Rubygem Issue 1551
- 2.3.4
- 2.2.7
script: rake test
deploy:
  provider: rubygems
  api_key:
    secure: Dl4WbcanhB309P6YUXpm17rbvzChEDJLdkDGNOhLaIACnVStn598g6qzyl9zmJwIBxOpypnM+QklOhJslQ6d6J/9g8guwYMYgHTmNd7GtRlZOw1Gi8bG2+LTIrTiwt92syoxZEfoCuaY9zQ/xlUL1SUE/i7fIAIcc68HIwlCtUfqnbBm6WvGHyz1CRWuglyLIHO0twN7DDO0upMuU0XNPhJ1T65GTB1VW1JvUuG3RUkNWRLGeTknXNS37ZaFHj+RoRxogAx862sq2aIShu7fuK3BfQizn7RlOQeAY6y1yV1c/SNUCMtROK5zGdm9uIZniACmuJHRPDHRRiRcNy6NkwzGtKkPujILrhRGPiKdUbqqWNZEW6OhFK3d1lwatMU9iGyDRXMchRgrlil/6HFhrx3zA+nbTmBTWkiZ4EThfKjZkDNCqQ3W/hCn4e7LA2y3IMbYh72xeyhJhGMSJN+tszjS/Ym5UgsYxp5Gh0s8cTujDelCWJ7/kFJxpcurSqQ6NPMd3tyeOxtKivxV3BK1My2rhsi2oSvTh2DNo2YzSlNZCmuUChQcVrAqjylAYkF6ff+4iL5avL+VMf6HTClEdHgDRBcVfmIvCpNvpi90670nRm+EpOpuP1irQ1TprAUmjrCoJLxt5JF9g8cmtYy6ElM6nJH1Xq2LLyLNB28pyWs=
  gem: wallee-ruby-sdk
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.4.1"
    repo: wallee-payment/ruby-sdk